enable actions on hand snap points
GodotVR/godot-xr-tools pull request #666
Opened 2024-08-07 03:49 UTC by DanielKinsman

Handling pickables like two handed guns where you only want the "trigger" hand to fire it [seems complex](https://github.com/GodotVR/godot-xr-tools/blob/master/assets/3dmodelscc0/models/sniper_rifle/firearm_trigger.gd#L58). I think it is simpler to add actions to the grab points instead of the pickable.

2024-08-09 01:47 UTC, DanielKinsman commented
This is a quick fix which can perhaps be solved in a more holistic way, so happy to close it in favour of something more comprehensive. During the XR meeting someone mentioned just passing the controller events on down to the object directly, that would be nice. Perhaps something like a "pressed" event which tells the object:

* what input was pressed
* what controller pressed it
* where that controller is holding me

2024-09-20 02:46 UTC, BastiaanOlij requested changes
Generally happy with this change except that it will break existing applications that implement the current action function.

The suggestions here is to change to keep both. So call `action` as is and leave the `action` implementation on `pickable.gd` as is currently.

Then call a new `controller_action` method that has the new code.

2024-09-26 03:33 UTC, Malcolmnixon reviewed
This is looking quite good - just a few minor checks and I think this will be ready to go in.

2024-09-26 03:33 UTC, Malcolmnixon commented on addons/godot-xr-tools/functions/function_pickup.gd
> +			picked_up_object.controller_action(_controller)
The has_method check should be used to check for the new controller_action method as well. I would recommend something like:
```gdscript
	if p_button == action_button_action and is_instance_valid(picked_up_object):
		if picked_up_object.has_method("action"):
			picked_up_object.action()
		if picked_up_object.has_method("controller_action"):
			picked_up_object.controller_action(_controller)
```

2024-09-26 03:33 UTC, Malcolmnixon commented on addons/godot-xr-tools/functions/function_pickup.gd
> +			picked_up_object.controller_action_release(_controller)
Same as the _on_button_pressed - this should check for the new method before calling it - something like:
```gdscript
	if p_button == action_button_action and is_instance_valid(picked_up_object):
		if picked_up_object.has_method("action_release"):
			picked_up_object.action_release()
		if picked_up_object.has_method("controller_action_release"):
			picked_up_object.controller_action_release(_controller)
```

2024-09-30 01:52 UTC, Malcolmnixon approved these changes
This looks good to me

2024-09-30 01:57 UTC, BastiaanOlij approved these changes
Happy with the changes, great work.

2024-09-30 02:04 UTC, merged